/*
 * File: app/store/TemplateStr_RunningWidget.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TemplateMetro.store.TemplateStr_RunningWidget', {
    extend: 'Ext.data.Store',

    requires: [
        'TemplateMetro.model.TemplateMdl_App'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'TemplateMetro.model.TemplateMdl_App',
            storeId: 'TemplateStr_RunningWidget'
        }, cfg)]);
    },

    TemplateStr_RunningWidget_isNotRunning: function(record) {
        if(record && record.get)
        {
            var app_id = record.get("app_id");
            var multirunning = record.get("multirunning");
            var found = this.find("app_id",app_id);
            return (found===-1 || (found !== -1 && multirunning));
        }
        return false;

    }

});