/*
 * File: app/view/W8Preloader.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TemplateMetro.view.W8Preloader', {
    extend: 'Ext.window.Window',
    alias: 'widget.metropreloader',

    mixins: {
        preloader: 'CloudCommonComponent.view.MetroPreloader'
    },
    requires: [
        'CloudCommonComponent.view.MetroPreloader'
    ],

    height: 250,
    width: 400,
    title: 'My Window',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforerender: {
                    fn: me.onWindowBeforeRender,
                    scope: me
                },
                render: {
                    fn: me.onWindowRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onWindowBeforeRender: function(component, eOpts) {
        component.beforeRenderEvent();
    },

    onWindowRender: function(component, eOpts) {
         component.renderEvent();
    }

});