/*
 * File: app/model/TemplateMdl_AppPreference.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TemplateMetro.model.TemplateMdl_AppPreference', {
    extend: 'Ext.data.Model',

    mixins: {
        persistence: 'cloudLibrary.model.Persistent'
    },
    requires: [
        'Ext.data.Field'
    ],

    idProperty: '_id',

    fields: [
        {
            name: 'app_id'
        },
        {
            name: 'preferences'
        }
    ],

    constructor: function() {
        var me = this;
        me.processTemplateMdl_AppPreference(me);
        me.callParent(arguments);
    },

    processTemplateMdl_AppPreference: function(config) {
        this.configureModel(config);
    }

});