/*
 * File: app/controller/MainCnt.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TemplateMetro.controller.MainCnt', {
    extend: 'Ext.app.Controller',

    mixins: {
        mix: 'MetroMixin.controller.MainCnt'
    },

    mainCnt_onInit: function(callback, parameters, scope) {

        var preloader = parameters.preloader; //Use preloader to comunicate change of status during initialization

        console.log(parameters);

        //Don't Forget to call
        if(typeof callback === "function") callback.call(scope,parameters);


    },

    mainCnt_onStart: function(parameters) {

        console.log(parameters);

        var preloader = parameters.preloader;
        var prefs = parameters.preferences;

        /*Create the main view*/
        var win = this.MainCnt_getMainViewRef();
        win.prefs = prefs;

        prefs = null;
        parameters = null;

        preloader.dismiss(null,function(){
            //Show main View after preloader has been hidden
            win.show();
        },this);

    },

    mainCnt_onClose: function(callback, parameters, scope) {

    }

});
