/*
 * File: app/controller/TemplateCnt_tpl.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TemplateMetro.controller.TemplateCnt_tpl', {
    extend: 'Ext.app.Controller',

    mixins: {
        mix: 'MetroMixin.controller.TemplateCnt_tpl'
    },

    models: [
        'TemplateMdl_App',
        'TemplateMdl_AppPreference'
    ],
    stores: [
        'TemplateStr_RunningWidget',
        'TemplateStr_Apps',
        'TemplateStr_AppPreferences'
    ],

    tplCnt_initialize: function(application) {

    },

    tplCnt_deInitialize: function(application) {

    },

    tplCnt_dismiss: function() {

    },

    tplCnt_getCountRunningWdg: function() {

    },

    tplCnt_getCountAvailableWdg: function() {

    },

    onLaunch: function() {

        Ext.create('TemplateMetro.view.AppWindow_tpl', {renderTo: Ext.getBody()}).show();
    }

});
